### ISSUE TITLE
AddToReadingList not work

### ISSUE THREAD

**Issue by Binusz** [urbn/URBNShareKit#5]
You should add a NSURL type variable in "initWithActivityItems" part.

**Comment by ryang1428** [comment]
Could you give a bit more info or sample code here as well? What exactly are you trying accomplish that you cannot?

**Comment by Binusz** [comment]
My problem is the AddToReadingList icon not appear after i supply valid URL.

https://github.com/urbn/URBNShareKit/blob/master/Pod/Classes/URBNActivityViewController.m#L31

urlProvider type must be NSURL class, otherwise AddToReadingList item not appear.

More info; http://stackoverflow.com/a/19335205/966615

**Comment by ryang1428** [comment]
Thanks for the additional info. I'll look into this as soon as I can.

**Comment by ryang1428** [comment]
0.2.2 Was pushed to trunk with a fix for this issue. Thanks for reporting
